release: newton
osp_release: rhos-10
undercloud_image_url: file:///home/stack/images/osp10/undercloud.qcow2
overcloud_image_url: file:///home/stack/images/osp10/overcloud-full.tar
ipa_image_url: file:///home/stack/images/osp10/ironic-python-agent.tar
undercloud_install_script: "{{ jenkins_workspace }}/config/scripts/undercloud-install_osp10.sh.j2"
undercloud_customize_script: "{{ jenkins_workspace}}/config/scripts/undercloud-customize-script.sh.j2"

